config/routes.rb
Rails.application.routes.draw do
  resources :pins

  devise_for :users
  root "pins#index"
  get "about" => "pages#about"

  mount Attachinary::Engine => "/attachinary"

end

app/models/pin.rb
class Pin < ActiveRecord::Base

#	belongs_to :user
#	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "http://40.media.tumblr.com/tumblr_lojfcezDPQ1qasthro1_1280.jpg"
	#	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]
#end

belongs_to :user


	has_attachment  :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, accept: [:jpg, :png, :gif]
	 #has_attachment :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "http://icons.iconarchive.com/icons/oxygen-icons.org/oxygen/256/Status-image-missing-icon.png"
	 #validates_attachments :image, presence: true, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png"] }
	validates :image, presence: true
	validates :description, presence: true




end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         has_many :pins, dependent: :destroy

         validates :name, presence: true
        
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  	protect_from_forgery with: :exception
   before_filter :configure_permitted_parameters, if: :devise_controller?

   protected 

def configure_permitted_parameters
   devise_parameter_sanitizer.for(:sign_up) << :name
   devise_parameter_sanitizer.for(:account_update) << :name
 end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  	def home

	def about 
	end 

  	end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  

  def index
    @pins = Pin.all.order("created_at DESC").paginate(page: params[:page], :per_page => 10)
     
end

  def show
  

    #if @pin[:image_id].present?
    #   preloaded = Cloudinary::PreloadedFile.new(pin[:image_id])
    #    Verify signature by calling preloaded.valid?
    #   @pin.image_id = preloaded.identifier
    #end
  end

  def new
    @pin = current_user.pins.build
  end

  def edit
  end

  def create
    @pin = current_user.pins.build(pin_params)
    if @pin.save
      redirect_to @pin, notice: 'Pin was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if @pin.update(pin_params)
      redirect_to @pin, notice: 'Pin was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @pin.destroy
    redirect_to pins_url
  end

  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      #@pin = Pin.find_by(params[:id])
      @pin = Pin.find_by(id: params[:id])
    end

    def correct_user

      @pin = current_user.pins.find_by(id: params[:id])
      redirect_to pin_path, notice: "Not authorized to edit this pin" if @pin.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description, :image)

    end
end

  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-static-top navbar-default" role="navigation">
  <div class="container">  
 

    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>


    <div class="logo">
      
     <%= cl_image_tag("https://m2.behance.net/rendition/pm/24633901/disp/e1dfb7e8918ddab4b3549076cade4f7f.png", :width=>40, :crop=>:scale)%>
     </div>

    <%= link_to "PinApp" , root_path, class: "navbar-brand name"%>
      </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav navbar-right margin">

        
        <li><%= link_to raw('<span class="glyphicon glyphicon-home orange"></span>&nbsp;&nbsp;&nbsp;Home'), root_path %></li>        
        <li><%= link_to raw('<span class="glyphicon glyphicon-info-sign orange"></span>&nbsp;&nbsp;&nbsp;About'), about_path %></li>  
        <li><%= link_to raw('<span class="glyphicon glyphicon-cog orange"></span>&nbsp;&nbsp;&nbsp;Account Settings'), edit_user_registration_path %></li> 
        <% if user_signed_in? %>  
        <li><%= link_to raw('<span class="glyphicon glyphicon-plus orange"></span>&nbsp;&nbsp;&nbsp;New Pin'), new_pin_path %></li> 
        <li><%= link_to raw('<span class="glyphicon glyphicon-off orange"></span>&nbsp;&nbsp;&nbsp;Log out'), destroy_user_session_path, method: :delete %></li> 
        <% else %>
         <li><%= link_to raw('<span class="glyphicon glyphicon-play orange"></span>&nbsp;&nbsp;&nbsp;Sign in'), new_user_session_path %></li> 
        <% end %> 
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
		

</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyfirstappNew</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
 	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %> 
  <%= csrf_meta_tags %>
  <%= cloudinary_js_config %>
  

	<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

		<%= render 'layouts/header' %>
		<div class="container">

		<% flash.each do |name, msg| %>
  	<%= content_tag(:div, msg, class: "alert alert-info") %>
		<% end %>

		<%= yield %>
		</div>


</body>
</html>

app/views/pages/_home.html.erb
<br><br><br><center>

<!-- <div class="jumbotron"> -->
	
	<h1 class="bring-front">Welcome to PinApp!</h1>
	

	<p>
	<%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
	<%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
	</p>
<!-- </div> -->
	</center>

app/views/pages/about.html.erb
<br><br>
		<div class="jumbotron center">
		<h1>about us</h1>
		<p>Ready to get in touch with us?  <%= link_to "Contact us!", 
		"contact_form/new", class: "btn btn-primary btn-lg" %>
		</p>

		<div id="bg2">
 	<img src="http://res.cloudinary.com/htt53jedq/image/upload/v1433549879/8bc72ed7_el9cvg.jpg" apages#contactlt="">
	</div>

app/views/pins/_form.html.erb
<%= form_for @pin, html: { multipart: true } do |f| %>
  
  <% if @pin.errors.any? %>

    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>




<div class="panel-body margin20">

    <div class="form-group">
        <%= f.label :image, as: :attachinary%>
        <%= f.attachinary_file_field :image, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_field :description, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.submit class: "btn btn-primary" %>
      </div>
</div>

<% end %>

app/views/pins/edit.html.erb
<div class="panel-heading">
<h1>Editing Pin</h1>
</div>
<%= render 'form' %>

<div class="panel-footer">
<%= link_to @pin do %>
<span class="glyphicon glyphicon-eye-open black"></span>
	Show
	<% end %>

<%= link_to pins_path do %>
	<span class="glyphicon glyphicon-share black"></span>
	Back
	<% end %>
</div>

app/views/pins/index.html.erb
<%= render 'pages/home' unless user_signed_in?  %>

<div id="pins" class="transitions-enabled">

       <% @pins.each do |pin| %>
          <div class="container">
          <div class="box panel panel-default">
          
             <% if pin.image.present?  %>
                  <%= link_to pin do %>
                  <%= cl_image_tag(pin.image.path) %>
            <% end %>
           <% else %>         
                  <%= cl_image_tag('no-image-found_jqqruy') %>                 
             <% end %>    

          
            <div class="pin-panel-body">
      
            <%= pin.description %> <br>
            <strong><%= pin.user.name if pin.user %></strong>
       
            <% if pin.user == current_user && user_signed_in? %>
                <div class="actions">
                  <%= link_to edit_pin_path(pin) do %>
                    <span class="glyphicon glyphicon-edit black"></span>
                      Edit
                         <% end %>

                  <%= link_to pin, method: :delete, data: { confirm: 'Are you sure?' } do %>
                     <span class="glyphicon glyphicon-trash black"></span>
                      Delete
                        

                            </div>    

                         <% end %>     
                       <% end %>
                      </div> 
                    </div>  
                  </div>      

                  
               <% end %>

              <div class="text-center">

            
                   <%= will_paginate @pins, renderer: BootstrapPagination::Rails %>
             
                 </div>  
                  

app/views/pins/new.html.erb
<div class="panel-heading">
<h1>New Pin</h1>
</div>

<%= render 'form' %>


	<div class="panel-footer">
	<%= link_to pins_path do %>
	<span class="glyphicon glyphicon-share black"></span>
	Back
	<% end %>
	</div>

app/views/pins/show.html.erb
<div class="header">
	<div class="row">
		 <div class="col-md-offset-2 col-md-8">

		    <div class="panel panel-default">
		      <div class="panel-heading center">
		      	<%= cl_image_tag(@pin.image.path)%>
		     	</div>
		     		<div class="panel-body">
			 				<p><%= @pin.description %></p>
			 			</div>
		     		<div class="panel-footer"> 

		     		<%= link_to pins_path do %>
							<span class="glyphicon glyphicon-share black"></span>
				  		Back
						  						
				  	<% end %>

						<% if @pin.user == current_user %>			    
			  		<%= link_to edit_pin_path(@pin) do %>
			  		<span class="glyphicon glyphicon-edit black"></span>
				  	Edit
		  			</div>	
				 		 	<% end %> 
								<%end%> 